export const signals = {
  slimePosition: 'SLIME_POSITION',
  slimeItemCollect: 'SLIME_COLLECTS_ITEM',
  slimeInteraction: 'SLIME_INTERACTION',
  slimeContact: 'SLIME_CONTACT',
  sceneExit: 'SCENE_EXIT',
  levelChanging: 'LEVEL_CHANGING',
  levelChanged: 'LEVEL_CHANGED',
  stateChanged: 'GAME_STATE_CHANGE',
  scoreUpdate: 'SCORE_CHANGE',
  startTextInteraction: 'START_TEXT_INTERACTION',
  endTextInteraction: 'END_TEXT_INTERACTION',
  arrowMovement: 'ARROW_MOVEMENT',
  arrowStep: 'ARROW_MOVEMENT_SINGLE',
  gameAction: 'GAME_ACTION',
};
